#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'vagabond', '1.0.4'
cookbook 'lxc', '1.1.4'
cookbook 'chef-server-populator', '0.3.0'

cookbook 'chef-server', '~> 2.1'
